# Generated by Django 2.0.2 on 2018-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='result',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя и возраст'),
        ),
    ]
