# Generated by Django 2.0.2 on 2018-02-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advanteges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Плюсы',
                'verbose_name': 'Плюсы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_count', models.IntegerField(verbose_name='Кол-во видео-уроков')),
                ('hour_count', models.IntegerField(verbose_name='Кол-во часов')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name_plural': 'видео-курсы',
                'verbose_name': 'видео-курс',
            },
        ),
        migrations.AddField(
            model_name='advanteges',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
