# Generated by Django 2.0.2 on 2018-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(default='None', upload_to='media/video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media/images'),
        ),
    ]
