# Generated by Django 2.0.2 on 2018-02-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180217_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(default=None, upload_to='media/video'),
        ),
    ]
