# Generated by Django 2.0.2 on 2018-02-17 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180217_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='advanteges',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanteges', to='course.Course'),
        ),
    ]
