# Generated by Django 2.0.2 on 2018-02-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180217_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(default=None, upload_to='video', verbose_name='Видео'),
        ),
    ]
