# Generated by Django 2.0.2 on 2018-02-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_faq_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
