# Generated by Django 2.0.2 on 2018-02-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20180218_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='extra',
            field=models.TextField(default='Default', verbose_name='Прочее'),
        ),
        migrations.AddField(
            model_name='course',
            name='food',
            field=models.TextField(default='Default', verbose_name='Питание'),
        ),
    ]
