# Generated by Django 2.0.2 on 2018-02-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20180222_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(default='default', max_length=255, verbose_name='Заголовок'),
        ),
    ]
