# Generated by Django 2.0.2 on 2018-03-13 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0019_auto_20180313_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(through='course.UsersInCourse', to=settings.AUTH_USER_MODEL, verbose_name='Оплатившие'),
        ),
    ]
