# Generated by Django 2.0.2 on 2018-03-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expire',
            field=models.IntegerField(default=40, verbose_name='Период действия(в днях)'),
        ),
    ]
