# Generated by Django 2.0.2 on 2018-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20181107_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='old_cost',
            new_name='cost_discount',
        ),
    ]
