# Generated by Django 2.0.2 on 2018-02-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
